import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex min-h-screen flex-col justify-center items-center p-4">
        <nav className="flex flex-row items-center p-2 rounded-xl gap-3 bg-blue-600 cursor-pointer transition-all duration-300  hover:gap-5  hover:font-bold mb-7 ">
          <div className=" hover:text-black"><Link href="/">Home</Link></div>
          <div className=" hover:text-black"><Link href="/about">About</Link></div>
          <div className=" hover:text-black"><Link href="/techstack">TechStack</Link></div>
          <div className=" hover:text-black"><Link href="/portfolio">Porfolio</Link></div>
          <div className=" hover:text-black"><Link href="/blog">Blog</Link></div>
          <div className=" hover:text-black"><Link href="/contact">Contact</Link></div>
        </nav>
        <div>{children}</div>
        <footer className="flex flex-row justify-between items-center w-full p-4 mt-32 border-t-2 border-zinc-500">
        <div>© 2024 Wassim. All Rights Reserved.</div>
       
      
      </footer>
      </div>
      </body>
    </html>
  );
}
